// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20:43:07 1/4/2026
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/laragon/www/ecom-wms/storefront-pwa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/plugins/**/*.{js,ts,mjs}","C:/laragon/www/ecom-wms/storefront-pwa/composables/**/*.{js,ts,mjs}","C:/laragon/www/ecom-wms/storefront-pwa/utils/**/*.{js,ts,mjs}","C:/laragon/www/ecom-wms/storefront-pwa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/ecom-wms/storefront-pwa/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;